Repository duckduckgo/content-scope-scripts, pull requests merged in 2025-07, with the labels that each got.

#1788 NTP: Add omnibar page to new tab children list
  special-pages/pages/new-tab/app/new-tab.md
Labels: documentation

#1790 NTP: Add enableAi config to control Duck.ai tab visibility in Omnibar
  special-pages/pages/new-tab/app/omnibar/components/Omnibar.js
  special-pages/pages/new-tab/app/omnibar/components/OmnibarConsumer.js
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.js
  special-pages/pages/new-tab/app/omnibar/mocks/omnibar.mock-transport.js
  special-pages/pages/new-tab/app/omnibar/strings.json
  special-pages/pages/new-tab/messages/types/omnibar-config.json
  special-pages/pages/new-tab/public/locales/en/new-tab.json
  special-pages/pages/new-tab/types/new-tab.ts
Labels: enhancement

#1798 NTP: Basic omnibar integration tests
  special-pages/pages/new-tab/app/omnibar/integration-tests/omnibar.page.js
  special-pages/pages/new-tab/app/omnibar/integration-tests/omnibar.spec.js
  special-pages/pages/new-tab/integration-tests/new-tab.page.js
  special-pages/playwright.config.js
Labels: tests

#1811 NTP: Style Omnibar to match specs
  special-pages/pages/history/app/components/SearchForm.js
  special-pages/pages/new-tab/app/components/Icons.js
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.js
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/Container.js
  special-pages/pages/new-tab/app/omnibar/components/Container.module.css
  special-pages/pages/new-tab/app/omnibar/components/Omnibar.js
  special-pages/pages/new-tab/app/omnibar/components/Omnibar.module.css
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.js
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/SuggestionList.module.css
  special-pages/pages/new-tab/app/omnibar/components/SuggestionsList.js
  special-pages/pages/new-tab/app/omnibar/components/SuggestionsList.module.css
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.js
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
  special-pages/pages/new-tab/app/omnibar/integration-tests/omnibar.page.js
  special-pages/pages/new-tab/app/omnibar/integration-tests/omnibar.spec.js
  special-pages/pages/new-tab/app/omnibar/strings.json
  special-pages/pages/new-tab/app/styles/ntp-theme.css
  special-pages/pages/new-tab/public/icons/Logo-Stacked.svg
  special-pages/pages/new-tab/public/locales/en/new-tab.json
Labels: enhancement

#1824 NTP: Set target to 'new-tab' and 'new-window' properly when submitting Omnibar
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.js
  special-pages/pages/new-tab/app/omnibar/components/useSuggestions.js
  special-pages/pages/new-tab/app/omnibar/integration-tests/omnibar.spec.js
Labels: bug

#1827 NTP: Omnibar i18n
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.js
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.js
  special-pages/pages/new-tab/app/omnibar/strings.json
  special-pages/pages/new-tab/public/locales/de/new-tab.json
  special-pages/pages/new-tab/public/locales/en/new-tab.json
  special-pages/pages/new-tab/public/locales/es/new-tab.json
  special-pages/pages/new-tab/public/locales/fr/new-tab.json
  special-pages/pages/new-tab/public/locales/it/new-tab.json
  special-pages/pages/new-tab/public/locales/nl/new-tab.json
  special-pages/pages/new-tab/public/locales/pl/new-tab.json
  special-pages/pages/new-tab/public/locales/pt/new-tab.json
  special-pages/pages/new-tab/public/locales/ru/new-tab.json
Labels: enhancement

#1828 cache the result of isAppleSilicon()
  injected/src/utils.js
Labels: patch

#1839 NTP Omnibar: Grow container when focused to accomodate focus ring
  special-pages/pages/new-tab/app/omnibar/components/Container.module.css
Labels: bug

#1840 NTP Omnibar: Refactor TabSwitcher to use CSS for blob and CSS grid for sizing
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.js
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
Labels: bug

#1846 NTP: Fix omnibar colour when using a custom background
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
  special-pages/pages/new-tab/app/styles/ntp-theme.css
Labels: bug

#1851 NTP: Fix WebKit blur event bug in omnibar components
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.js
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.js
Labels: bug

#1852 NTP: Update Omnibar placeholder and Hide/Show Duck.ai localisations
  special-pages/pages/new-tab/public/locales/de/new-tab.json
  special-pages/pages/new-tab/public/locales/es/new-tab.json
  special-pages/pages/new-tab/public/locales/fr/new-tab.json
  special-pages/pages/new-tab/public/locales/it/new-tab.json
  special-pages/pages/new-tab/public/locales/nl/new-tab.json
  special-pages/pages/new-tab/public/locales/pl/new-tab.json
  special-pages/pages/new-tab/public/locales/pt/new-tab.json
  special-pages/pages/new-tab/public/locales/ru/new-tab.json
Labels: bug

#1853 NTP: Improve TabSwitcher hover interactions and visual design
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
Labels: enhancement

#1858 NTP: Fix disappearing search icon in WebKit
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
Labels: bug

#1863 NTP: Adjust omnibar colours to match native apps and Figma
  special-pages/pages/new-tab/app/omnibar/components/AiChatForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/Container.module.css
  special-pages/pages/new-tab/app/omnibar/components/SearchForm.module.css
  special-pages/pages/new-tab/app/omnibar/components/SuggestionsList.module.css
  special-pages/pages/new-tab/app/omnibar/components/TabSwitcher.module.css
  special-pages/pages/new-tab/app/styles/ntp-theme.css
Labels: bug
